# Generated by Django 5.1.2 on 2024-10-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_de_tarefas', '0002_alter_tarefasmodel_data_criacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefasmodel',
            name='nome_usuario',
        ),
        migrations.AddField(
            model_name='tarefasmodel',
            name='responsavel',
            field=models.CharField(db_column='responsavel', default='Sem responsavel', max_length=60),
            preserve_default=False,
        ),
    ]
