# Generated by Django 5.1.2 on 2024-10-10 16:50

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro_de_tarefas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempoDeTrabalhoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_do_registro', models.DateField(db_column='data_do_registro', db_default=django.db.models.functions.datetime.Now())),
                ('tempo_trabalhado_minutos', models.IntegerField(db_column='tempo_de_trabalho_em_minutos')),
                ('descricao_trab_realizado', models.TextField(db_column='descricao_do_trabalho_realizado', max_length=360)),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro_de_tarefas.tarefasmodel')),
            ],
        ),
    ]
