# Generated by Django 5.1.2 on 2024-10-10 20:35

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempo_de_trabalho', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempodetrabalhomodel',
            name='tempo_trabalhado_horas',
            field=models.IntegerField(db_column='tempo_de_trabalho_em_horas', default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tempodetrabalhomodel',
            name='data_do_registro',
            field=models.DateTimeField(db_column='data_do_registro', db_default=django.db.models.functions.datetime.Now()),
        ),
    ]
