# Generated by Django 5.1.2 on 2024-10-11 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempo_de_trabalho', '0002_tempodetrabalhomodel_tempo_trabalhado_horas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempodetrabalhomodel',
            name='tempo_trabalhado_horas',
        ),
        migrations.RemoveField(
            model_name='tempodetrabalhomodel',
            name='tempo_trabalhado_minutos',
        ),
        migrations.AddField(
            model_name='tempodetrabalhomodel',
            name='tempo_trabalhado',
            field=models.TimeField(db_column='tempo_de_trabalho', default='00:00'),
            preserve_default=False,
        ),
    ]
