# Generated by Django 5.1.2 on 2024-10-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempo_de_trabalho', '0003_remove_tempodetrabalhomodel_tempo_trabalhado_horas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempodetrabalhomodel',
            name='tempo_trabalhado',
            field=models.TimeField(db_column='tempo_trabalhado'),
        ),
    ]
