# Generated by Django 5.1.2 on 2024-10-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempo_de_trabalho', '0004_alter_tempodetrabalhomodel_tempo_trabalhado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempodetrabalhomodel',
            name='tempo_trabalhado',
            field=models.DurationField(db_column='tempo_trabalhado'),
        ),
    ]
